### ISSUE TITLE
Connection pool connections are not released？

### ISSUE THREAD

**Issue by wendelwall** [linux-china/mybatis-r2dbc#3]
我使用了连接池遇到了连接池链接不释放问题，我初始化连接池大小10，当我的查询十次以后，就不能再次查询了,查询卡住。

**Comment by naah69** [comment]
+1，楼上的兄弟有解决方案吗

**Comment by naah69** [comment]
it has be fixed in #6

**Comment by marepop** [comment]
Any info on when will this be merged?

**Comment by linux-china** [comment]
Sorry for delay answer.   merged.
